### ISSUE TITLE
Migrator config parsing

### ISSUE THREAD

**Issue by deruzh** [derandomize/omnia#5]
We need migrator to parse config to create db later. Config shoud be yaml file, with this structure:
```
config:
    prefer_local: true
    config_table_name: omnia_config
    feature_name: omina_id

open_search:
    host: xxx
    port: xxx
    username: xxx
    password: xxx 

database:
     type: 'postgresql' # only postgresql is allowed now
     params:
         database_name: xxx
         host: xxx
         port: xxx
         username: xxx
         password: xxx

```
